import React, { useState } from 'react';
import { CrossIcon, BookIcon, ChevronDownIcon, ChevronUpIcon, ShieldIcon } from './Icons.jsx';

export function PrivacyModal({ isOpen, onClose }) {
  if (!isOpen) return null;
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-card" style={{ maxWidth: '520px' }} onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="card-title">
            <ShieldIcon size={16} />
            <span>Internal Data Privacy Policy (Stub)</span>
          </div>
          <button type="button" onClick={onClose} style={{ color: 'var(--text-muted)' }}>
            <CrossIcon size={15} />
          </button>
        </div>
        <div className="modal-body" style={{ fontSize: '0.8rem', lineHeight: 1.4 }}>
          <p><strong>1. Internal System Scope:</strong> Returns Manager is a tenant-isolated decision support system for authorized fulfillment center personnel.</p>
          <p><strong>2. Data Boundaries:</strong> All inspection photographs, customer orders, and disposition logs are partitioned by organization ID. Cross-tenant data leakage is strictly blocked at the query layer.</p>
          <p><strong>3. Non-Public Data:</strong> This tool does not track public consumer browsing or set non-essential marketing cookies.</p>
        </div>
        <div className="modal-footer">
          <button type="button" className="btn-secondary" onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}

export function TermsModal({ isOpen, onClose }) {
  if (!isOpen) return null;
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-card" style={{ maxWidth: '520px' }} onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="card-title">
            <BookIcon size={16} />
            <span>Operating Terms of Service (Stub)</span>
          </div>
          <button type="button" onClick={onClose} style={{ color: 'var(--text-muted)' }}>
            <CrossIcon size={15} />
          </button>
        </div>
        <div className="modal-body" style={{ fontSize: '0.8rem', lineHeight: 1.4 }}>
          <p><strong>1. Operator Responsibility:</strong> Decisions generated by Returns Manager are decision-support recommendations. Operators maintain authority to override verdicts with documented audit justification.</p>
          <p><strong>2. Ground Truth Compliance:</strong> Operators must adhere to published Amazon condition scales and avoid inventing arbitrary condition grades.</p>
          <p><strong>3. Tenancy Integrity:</strong> Attempting to access units or evidence belonging to another tenant is a security violation.</p>
        </div>
        <div className="modal-footer">
          <button type="button" className="btn-secondary" onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}

export function FAQModal({ isOpen, onClose }) {
  const [openIndex, setOpenIndex] = useState(0);

  if (!isOpen) return null;

  const faqs = [
    {
      q: "How does the system handle ambiguous returns?",
      a: "Per Engineering Rule 4, UNCERTAIN is treated as a valid first-class outcome, never a failure. If lighting is obscured, a seal is ambiguous, or a product looks visually identical to a clone, the system outputs UNCERTAIN and routes the case to pending_review."
    },
    {
      q: "What is the difference between observed_state and amazon_condition?",
      a: "observed_state is a raw physical observation (e.g. factory_sealed, opened_unused, signs_of_use, damaged, empty_box, uncertain). amazon_condition is the official graded external condition (New, Used - Like New, Used - Very Good, Used - Good, Used - Acceptable, Unacceptable, Uncertain)."
    },
    {
      q: "What happens when an operator overrides an AI decision?",
      a: "Overrides never delete data. The system preserves the original AI recommendation, the revised disposition, the operator ID, timestamp, and the required operational disagreement reason."
    },
    {
      q: "How does tenancy isolation work?",
      a: "Data and image paths are partitioned at the query level. Even if an operator in org_demo_alpha attempts to load a unit ID or image path from org_demo_bravo, access is denied with a 403 Permission Denied security alert."
    }
  ];

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-card" style={{ maxWidth: '580px' }} onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="card-title">
            <BookIcon size={16} />
            <span>Operator Onboarding and FAQ</span>
          </div>
          <button type="button" onClick={onClose} style={{ color: 'var(--text-muted)' }}>
            <CrossIcon size={15} />
          </button>
        </div>
        <div className="modal-body">
          {faqs.map((faq, idx) => (
            <div key={idx} style={{ border: '1px solid var(--border-color)', borderRadius: '3px', overflow: 'hidden' }}>
              <div
                style={{ padding: '0.6rem 0.75rem', background: 'var(--bg-subtle)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer', fontWeight: 600, fontSize: '0.78rem' }}
                onClick={() => setOpenIndex(openIndex === idx ? -1 : idx)}
              >
                <span>{faq.q}</span>
                {openIndex === idx ? <ChevronUpIcon size={13} /> : <ChevronDownIcon size={13} />}
              </div>
              {openIndex === idx && (
                <div style={{ padding: '0.65rem 0.75rem', fontSize: '0.75rem', color: 'var(--text-main)', lineHeight: 1.4, background: 'var(--bg-surface)' }}>
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
        <div className="modal-footer">
          <button type="button" className="btn-secondary" onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}
