import React, { useState } from 'react';
import { CrossIcon, BookIcon, ChevronDownIcon, ChevronUpIcon, ShieldIcon } from './Icons.jsx';

export function PrivacyModal({ isOpen, onClose }) {
  if (!isOpen) return null;
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-card" style={{ maxWidth: '520px' }} onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="card-title">
            <ShieldIcon size={16} />
            <span>Internal Data Privacy Policy (Stub)</span>
          </div>
          <button type="button" onClick={onClose} style={{ color: 'var(--text-muted)' }}>
            <CrossIcon size={15} />
          </button>
        </div>
        <div className="modal-body" style={{ fontSize: '0.8rem', lineHeight: 1.4 }}>
          <p><strong>1. Internal System Scope:</strong> Returns Manager is a tenant-isolated decision support system for authorized fulfillment center personnel.</p>
          <p><strong>2. Data Boundaries:</strong> All inspection photographs, customer orders, and disposition logs are partitioned by organization ID. Cross-tenant data leakage is strictly blocked at the query layer.</p>
          <p><strong>3. Non-Public Data:</strong> This tool does not track public consumer browsing or set non-essential marketing cookies.</p>
        </div>
        <div className="modal-footer">
          <button type="button" className="btn-secondary" onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}

export function TermsModal({ isOpen, onClose }) {
  if (!isOpen) return null;
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-card" style={{ maxWidth: '520px' }} onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="card-title">
            <BookIcon size={16} />
            <span>Operating Terms of Service (Stub)</span>
          </div>
          <button type="button" onClick={onClose} style={{ color: 'var(--text-muted)' }}>
            <CrossIcon size={15} />
          </button>
        </div>
        <div className="modal-body" style={{ fontSize: '0.8rem', lineHeight: 1.4 }}>
          <p><strong>1. Operator Responsibility:</strong> Decisions generated by Returns Manager are decision-support recommendations. Operators maintain authority to override verdicts with documented audit justification.</p>
          <p><strong>2. Ground Truth Compliance:</strong> Operators must adhere to published Amazon condition scales and avoid inventing arbitrary condition grades.</p>
          <p><strong>3. Tenancy Integrity:</strong> Attempting to access units or evidence belonging to another tenant is a security violation.</p>
        </div>
        <div className="modal-footer">
          <button type="button" className="btn-secondary" onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}

export function FAQModal({ isOpen, onClose }) {
  const [openIndex, setOpenIndex] = useState(0);

  if (!isOpen) return null;

  const faqs = [
    {
      q: "What happens when photos are not clear?",
      a: "If lighting is dark, blurry, or an item cannot be clearly seen, the assistant marks the result as 'Needs human checking'. This lets an operator inspect the physical item directly rather than making a wrong call."
    },
    {
      q: "How does the assistant decide on an item's condition?",
      a: "The assistant checks for signs of wear, opened packaging, scratches, and missing items. It assigns a simple condition rating like 'Like new', 'Lightly used', or 'Damaged' and explains why in plain language."
    },
    {
      q: "Can I change an assistant recommendation?",
      a: "Yes. You have full authority to override any recommendation. When you change a decision, simply select the new action and provide a quick reason. The original suggestion is saved in the record history for tracking."
    },
    {
      q: "Is my warehouse facility data isolated?",
      a: "Yes. Each facility has its own secure space. Staff only see returns and photos assigned to their facility location."
    }
  ];

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-card" style={{ maxWidth: '580px' }} onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="card-title">
            <BookIcon size={16} />
            <span>Operator Guide & FAQ</span>
          </div>
          <button type="button" onClick={onClose} style={{ color: 'var(--text-muted)' }} aria-label="Close modal">
            <CrossIcon size={15} />
          </button>
        </div>
        <div className="modal-body" style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          {faqs.map((faq, idx) => (
            <div key={idx} style={{ border: '1px solid var(--border-color)', borderRadius: '4px', overflow: 'hidden' }}>
              <div
                style={{ padding: '0.65rem 0.85rem', background: 'var(--bg-subtle)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer', fontWeight: 600, fontSize: '0.82rem' }}
                onClick={() => setOpenIndex(openIndex === idx ? -1 : idx)}
              >
                <span>{faq.q}</span>
                {openIndex === idx ? <ChevronUpIcon size={13} /> : <ChevronDownIcon size={13} />}
              </div>
              {openIndex === idx && (
                <div style={{ padding: '0.75rem 0.85rem', fontSize: '0.8rem', color: 'var(--text-main)', lineHeight: 1.5, background: 'var(--bg-surface)' }}>
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
        <div className="modal-footer">
          <button type="button" className="btn-secondary" onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}
